### PR TITLE
CANS-932. Improve performance for Read Staff Latest Assessments operation

### PR DESCRIPTION
**Pull request by denys-davydov**
## JIRA
https://osi-cwds.atlassian.net/browse/CANS-932

## Description
Previously the Read Staff Latest Assessments operation returned all the assessments that the user created/updated (and then the frontend filtered and sorted the records). The approach led to performance degradation for active users who had worked on a lot of assessments. With this PR the operation is reworked so that it returns only 3 records that are already filtered by IN_PROGRESS status and ordered by created/updated timestamp. 
The performance was tested on developers laptop and showed the following results for 40,000 assessments:
NEW approach: median for 2 users is 82ms on 2000 calls
OLD approach: FAILS

N.B. Goes along with https://github.com/ca-cwds/cans/pull/434

## Tests
- [ ] I used TDD to develop the feature
- [ ] I have included unit tests
- [x] I have included new acceptance tests or modified existing ones
- [ ] I have included other tests

## Types of changes

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (No behavioral changes)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [x] I ran all my tests locally which were green.
- [x] My code adds no new issues to Code Climate
- [x] I ran all the linters and static analyzers for the project (SonarQube, eslint, rubocop, etc).
- [x] My code is in a stable state ready to be deployable, but not necessarily complete.

### CODE REVIEW

**Comment by denys-davydov** [comment]
@wmitchell-cambria What you describe is a very good approach, but I am not sure it is justified to use it in our situation. When we have hundreds of users online it is applicable and brings tons of value though.

**Comment by wmitchell-cambria** [comment]
In the days leading up to a release, I think it is all the more important. Breaking Integration will disrupt testing and other last minute bug fixes.

**Comment by denys-davydov** [comment]
@wmitchell-cambria We've never used the approach previously, as well as the described attitude to downtime, hence deployment of 1.1 into the production environment will go along with downtime anyway. So I still think that it is not worth the candle as of now. 
From my point of view, we can benefit from the approach when we have a lot of users, continuous delivery, multiple different clients for our backend and strict business rules about downtime. 

P.S. 10 minutes downtime for Integration was never a big concern, I believe.

**Comment by wmitchell-cambria** [comment]
All right, I'll leave it to you two. I do standby the approach for future cases, though.

**Pull request merged**
