### PR TITLE
CANS-432: Update cans-api to use system-information json format

### PR DESCRIPTION
**Pull request by SergiiRedchuk**
## Description
Improvement of reusable AbstractSystemInformationResource

https://osi-cwds.atlassian.net/browse/CANS-432

## Types of changes
- [x] Refactoring (No behavioral changes)

### CODE REVIEW

**Comment by SashaKyz** [comment]
retest this please

**Comment by SergiiRedchuk** [comment]
retest this please

**Comment by denys-davydov** [comment]
retest this please

**Comment by denys-davydov** [comment]
retest this please

**Pull request merged**
