### PR TITLE
CANS-348. Delete /assessments/_start endpoint as a redundant one

### PR DESCRIPTION
**Pull request by denys-davydov**
## Description
https://osi-cwds.atlassian.net/browse/CANS-348

The approach we are taking is to remove (delete) the endpoint, therefore the endpoint is not in swagger at all.

## Tests
- [ ] I used TDD to develop the feature
- [ ] I have included unit tests
- [ ] I have included new acceptance tests or modified existing ones
- [ ] I have included other tests

## Types of changes

- [ ] New feature (non-breaking change which adds functionality)
- [x] Refactoring (No behavioral changes)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [x] I ran all my tests locally which were green.
- [ ] My code adds no new issues to Code Climate
- [x] I ran all the linters and static analyzers for the project (SonarQube, eslint, rubocop, etc).
- [x] My code is in a stable state ready to be deployable, but not necessarily complete.
- [x] I promise on my honor as a CWDS developer to ensure I don't break the build, to check linters, use best practices, to leave the code in better shape than I found it, and to have a good day.

### CODE REVIEW

**Comment by denys-davydov** [comment]
retest this please

**Comment by edgibbs** [comment]
retest this please

**Comment by LeonidMarushevskyi** [comment]
retest this please

**Comment by denys-davydov** [comment]
retest this please

**Comment by denys-davydov** [comment]
Retest this please

**Comment by denys-davydov** [comment]
retest this please

**Pull request merged**
