### PR TITLE
CANS-340 Convert Domain titles from upperCase to titleCase

### PR DESCRIPTION
**Pull request by abelayt**
## Tests
- [ ] I used TDD to develop the feature
- [ ] I have included unit tests
- [ ] I have included new acceptance tests or modified existing ones
- [ ] I have included other tests

## Types of changes

- [ ] New feature (non-breaking change which adds functionality)
- [x] Refactoring (No behavioral changes)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] I ran all my tests locally which were green.
- [x] My code adds no new issues to Code Climate
- [ ] I ran all the linters and static analyzers for the project (SonarQube, eslint, rubocop, etc).
- [ ] My code is in a stable state ready to be deployable, but not necessarily complete.
- [x] I promise on my honor as a CWDS developer to ensure I don't break the build, to check linters, use best practices, to leave the code in better shape than I found it, and to have a good day.

### CODE REVIEW

**Comment by wmitchell-cambria** [comment]
What is the .xlsx file? Is it the same as that csv?

**Comment by abelayt** [comment]
> What is the .xlsx file? Is it the same as that csv?

The .xlsx file has 3 pages, cans_domains, cans_items and Domain_items. The cans_domains page
is where we changed the Domain titles from upper to title case and exported this to cans_domains.csv.

**Comment by denys-davydov** [comment]
@wmitchell-cambria Csv files are used to generate liquibase scripts that describe an instrument (a kind of template for assessment form). The excel file is our convenient way to edit the instrument. So we change the excel as per new requirements, export its pages to 3 csv files and run a tool that generates the scripts against those files. It is possible to do it without the excel file, but I find it convenient to have it so that any non-technical person can work on it if needed.

**Comment by wmitchell-cambria** [comment]
Makes a lot of sense, good to know!

**Pull request merged**
