### PR TITLE
CANS-943: Supervisor subordinate query fixed to not include end dated authorities

### PR DESCRIPTION
**Pull request by LeonidMarushevskyi**
## JIRA
https://osi-cwds.atlassian.net/browse/CANS-943

## Tests
- [ ] I used TDD to develop the feature
- [ ] I have included unit tests
- [ ] I have included new acceptance tests or modified existing ones
- [ ] I have included other tests

## Types of changes

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (No behavioral changes)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] I ran all my tests locally which were green.
- [ ] My code adds no new issues to Code Climate
- [ ] I ran all the linters and static analyzers for the project (SonarQube, eslint, rubocop, etc).
- [ ] My code is in a stable state ready to be deployable, but not necessarily complete.

### CODE REVIEW

**Comment by LeonidMarushevskyi** [comment]
retest this please

**Comment by denys-davydov** [comment]
Does it have any connection to this https://github.com/ca-cwds/api-core/pull/415 not yet merged PR?

**Comment by LeonidMarushevskyi** [comment]
Yes, it does have connection.

**Comment by LeonidMarushevskyi** [comment]
retest this please

**Comment by LeonidMarushevskyi** [comment]
retest this please

**Pull request merged**
